from fpdf import FPDF
import datetime
import os

class MineGuardPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, 'MineGuard Intelligence Report | CONFIDENTIAL', 0, 0, 'R')
            self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by MineGuard v2.0', 0, 0, 'C')

    def chapter_title(self, num, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(230, 230, 230)
        self.cell(0, 8, f"{num}. {label}", 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Times', '', 11)
        self.multi_cell(0, 6, text)
        self.ln()

def generate_pdf_report(data, output_path="MineGuard_Report.pdf"):
    """
    Generates a government-grade PDF report and saves it to output_path.
    """
    pdf = MineGuardPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    
    # --- PAGE 1: COVER PAGE ---
    pdf.add_page()
    pdf.ln(40)
    pdf.set_font('Arial', 'B', 24)
    pdf.cell(0, 10, "MineGuard", 0, 1, 'C')
    pdf.set_font('Arial', '', 14)
    pdf.cell(0, 10, "Automated Detection & Volumetric Estimation", 0, 1, 'C')
    
    pdf.ln(20)
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, f"Technical Report: {data.get('filename', 'Unknown')}", 0, 1, 'C')
    
    pdf.ln(10)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%d %B %Y')}", 0, 1, 'C')
    
    pdf.ln(40)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Prepared For: State Dept. of Mining", 0, 1, 'C')
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Prepared By: Team Mine Sector 256", 0, 1, 'C')

    # --- PAGE 2: SUMMARY ---
    pdf.add_page()
    pdf.chapter_title("1", "EXECUTIVE SUMMARY")
    
    illegal_area = data.get('illegal_area', 0)
    status_text = "NON-COMPLIANT" if illegal_area > 0 else "COMPLIANT"
    status_color = (200, 0, 0) if illegal_area > 0 else (0, 128, 0)

    pdf.set_font('Arial', 'B', 11)
    pdf.cell(40, 10, "Compliance Status: ", 0, 0)
    pdf.set_text_color(*status_color)
    pdf.cell(0, 10, status_text, 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    summary_text = (
        f"Analysis of {data.get('filename')} detected {illegal_area:,.2f} m2 of mining activity "
        f"outside the authorized boundary.\n"
        f"Total estimated illegal volume: {data.get('volume', 0):,.2f} m3 "
        f"(approx {data.get('trucks', 0):,} truckloads)."
    )
    pdf.chapter_body(summary_text)

    # Metrics Table
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(95, 8, "Metric", 1, 0, 'C', 1)
    pdf.cell(95, 8, "Value", 1, 1, 'C', 1)
    pdf.set_font('Arial', '', 10)
    
    metrics = [
        ("Verified Illegal Area", f"{illegal_area:,.2f} m2"),
        ("Avg. Pit Depth", f"{data.get('avg_depth', 0):,.2f} m"),
        ("Total Volume", f"{data.get('volume', 0):,.2f} m3"),
    ]
    
    for metric, value in metrics:
        pdf.cell(95, 8, metric, 1)
        pdf.cell(95, 8, value, 1, 1)

    # Save
    pdf.output(output_path)
    print(f"📄 PDF Report Generated: {output_path}")
    return output_path